version: '3.8'
services:
  marketPlace:
    build:
      context: .
      dockerfile: market_place/Dockerfile
    environment:
      - RECOMMENDATIONS_HOST=recommendations
    image: marketplace
    networks:
      - microservices
    ports:
      - 5000:5000

  recommendations:
    build:
      context: .
      dockerfile: recommendations/Dockerfile
    image: recommendations
    networks:
      - microservices
    volumes:
      - ./recommendations/prisma:/service/recommendations/prisma

  database:
    image: sqlite
    ports:
      - '8080:80'
    environment:
      - DATABASE_URL=file:microservice.db
    volumes:
      - ./recommendations/prisma:/service/recommendations/prisma
networks:
  microservices:
